### ISSUE TITLE
Macro Woes Tracking Issue

### ISSUE THREAD

**Issue by iwillspeak** [iwillspeak/feersum#13]
The current `syntax-rules` implementation generally _works_, but leaves a little to be desired. Namely:

 * [ ] No support for quoting of the ellipsis character `(... ...)`
 * [ ] Matching of patterns with `...` and `.` should be greedier with the repeat? Not sure about this one.
 * [ ] What if the ellipsis is also a literal identifier?
 * [ ] Macro hygiene 
   * [ ] Identifier hygiene
   * [ ] Scope hygiene
 * [ ] Missing location on expanded templates.
