### ISSUE TITLE
Interactive Scripting Improvements Tracking Issue

### ISSUE THREAD

**Issue by iwillspeak** [iwillspeak/feersum#35]
Our current REPL leaves a little to be desired. It would be nice if we had a better embeddable scripting API in the compiler so state could be carried across from one evaluation to the next.

 * [ ] Multi-statement support in the REPL.
 * [ ] #!r and #!nuget
 * [ ] `-e`, `--exec` immediate script mode
 * [ ] `-s`, `--script` script execute mode
 * [ ] Syntax highlighting in the REPL
