### ISSUE TITLE
Debugger Woes Tracking Issue

### ISSUE THREAD

**Issue by iwillspeak** [iwillspeak/feersum#36]
Our current debugger support is a bit rough around the edges. 

 * [x] Bound tree contains sequence points for debuging
 * [ ] Debuggable REPL. Embedded source in PDBs?
 * [x] Stop at entry, and step in.
 * [ ] IL Metadata sequence points by default (`IgnoreSymbolStoreSequencePoints`)
 * [ ] No symbol information for local names, or environment slots. 
 * [ ] Better lambda names. e.g. `foo_1::bar_0` not `lambda1::lambda0` if `(define (foo ..))` forms are used.
